---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/profiles/{email_prefix}@{email_sufix}/":
    get:
      summary: Obté la informació d'un perfil
      tags:
      - Perfils
      parameters:
      - name: email_prefix
        in: path
        required: true
        schema:
          type: string
      - name: email_sufix
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Operació exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  email:
                    type: string
                  username:
                    type: string
                  bio:
                    type: string
                  profile_picture:
                    type: string
                  timeline_events:
                    type: array
                    items:
                      type: object
                      properties:
                        project_id:
                          type: integer
                        project:
                          type: string
                        issue_id:
                          type: integer
                        issue:
                          type: string
                        message:
                          type: string
                        data:
                          type: string
                  watched_issues:
                    type: array
                    items:
                      type: object
                      properties:
                        project_id:
                          type: integer
                        project:
                          type: string
                        issue_id:
                          type: integer
                        issue:
                          type: string
        '404':
          description: Usuari no existent
    put:
      summary: Actualitza la informació d'un perfil
      tags:
      - Perfils
      parameters:
      - name: email_prefix
        in: path
        required: true
        schema:
          type: string
      - name: email_sufix
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Operació exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  email:
                    type: string
                  username:
                    type: string
                  bio:
                    type: string
                  profile_picture:
                    type: string
                  timeline_events:
                    type: array
                    items:
                      type: object
                      properties:
                        project_id:
                          type: integer
                        project:
                          type: string
                        issue_id:
                          type: integer
                        issue:
                          type: string
                        message:
                          type: string
                        data:
                          type: string
                  watched_issues:
                    type: array
                    items:
                      type: object
                      properties:
                        project_id:
                          type: integer
                        project:
                          type: string
                        issue_id:
                          type: integer
                        issue:
                          type: string
        '404':
          description: Usuari no existent
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                username:
                  type: string
                bio:
                  type: string
                avatar:
                  type: file
  "/projects/{project_id}/issues/{issue_id}/":
    get:
      summary: Obté la informació d'una Issue
      tags:
      - Issues
      parameters:
      - name: project_id
        in: path
        required: true
        schema:
          type: integer
      - name: issue_id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Operació exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  subject:
                    type: string
                  description:
                    type: string
                  status:
                    type: string
                  created_by_user_id:
                    type: integer
                  created_at:
                    type: string
                  issue_type:
                    type: string
                  severity:
                    type: string
                  priority:
                    type: string
                  limitDate:
                    type: string
                  blocked:
                    type: boolean
                  assigned_profile:
                    type: integer
                  timeline_events:
                    type: array
                    items:
                      type: object
                      properties:
                        profile_id:
                          type: integer
                        profile:
                          type: string
                        message:
                          type: string
                        date:
                          type: string
                  watched_issues:
                    type: array
                    items:
                      type: object
                      properties:
                        profile_id:
                          type: integer
                        profile:
                          type: string
        '404':
          description: Projecte o Issue no existent
servers:
- url: http://127.0.0.1:3000
